{ config, ... }:

{
  #homebrew packages
  homebrew = {
    enable = true;
    onActivation.autoUpdate = true;
    onActivation.upgrade = true;
    onActivation.cleanup = "zap"; # Uncomment this if you want all brew packages not defined in this file to be removed when updated
    brews = [
      "aircrack-ng"
      "borders"
      "brotli"
      "btop"
      "cairo"
      "capstone"
      "cava"
      "cheat"
      "curl"
      "elixir"
      "erlang"
      "fastfetch"
      "ffmpeg"
      "fftw"
      "fmt"
      "fontconfig"
      "freetype"
      "fribidi"
      "fzf"
      "gcc"
      "gettext"
      "gh"
      "ghc"
      "giflib"
      "git"
      "glfw"
      "glib"
      "gmp"
      "gnutls"
      "gogcli"
      "graphite2"
      "harfbuzz"
      "hashcat"
      "highway"
      "hwloc"
      "icu4c"
      "imath"
      "iniparser"
      "isl"
      "john-jumbo"
      "jpeg-turbo"
      "jpeg-xl"
      "lame"
      "libavif"
      "libdeflate"
      "libevent"
      "libidn2"
      "libimagequant"
      "liblinear"
      "libmpc"
      "libnghttp2"
      "libnghttp3"
      "libngtcp2"
      "libomp"
      "libpng"
      "libraqm"
      "libslirp"
      "libssh"
      "libssh2"
      "libtasn1"
      "libtiff"
      "libtool"
      "libunistring"
      "libusb"
      "libuv"
      "libvmaf"
      "libvpx"
      "libx11"
      "libxau"
      "libxcb"
      "libxdmcp"
      "libxext"
      "libxrender"
      "little-cms2"
      "lld"
      "llhttp"
      "llvm"
      "lua"
      "lz4"
      "lzo"
      "m-cli"
      "m4"
      "mas"
      "memo"
      "minizip"
      "mold"
      "mpdecimal"
      "mpfr"
      "ncurses"
      "nettle"
      "nmap"
      "node"
      "node"
      "numpy"
      "nushell"
      "obsidian-cli"
      "odin"
      "onefetch"
      "openblas"
      "openexr"
      "openjdk"
      "openjpeg"
      "openjph"
      "openssl@3"
      "opus"
      "p11-kit"
      "pcre2"
      "pillow"
      "pixman"
      "portaudio"
      "python"
      "qemu"
      "raylib"
      "readline"
      "remindctl"
      "rustup"
      "sdl2"
      "sevenzip"
      "signal-cli"
      "simdjson"
      "simdutf"
      "skhd"
      "sketchybar"
      "snappy"
      "sqlite"
      "stow"
      "supabase"
      "svt-av1"
      "tbb"
      "tokei"
      "unbound"
      "unixodbc"
      "uutils-coreutils"
      "uvwasi"
      "vde"
      "webp"
      "wxwidgets"
      "x264"
      "x265"
      "xorgproto"
      "xxhash"
      "xz"
      "yyjson"
      "zsh"
      "zstd"
    ];
    extraConfig = ''
      cask_args appdir: "~/Applications"
    '';
    taps = [
      "homebrew/cask"
      "homebrew/cask-drivers"
      "homebrew/cask-fonts"
      "homebrew/cask-versions"
      "homebrew/core"
      "homebrew/services"
    ];
    casks = [
      "aerospace"
      "ghostty"
      "raycast"
      "vlc"
      "anaconda"
      "github"
      "signal"
      "vscodium"
      "docker-desktop"
      "libreoffice"
      "tidal"
      "zed"
      "claude-code"
      "firefox"
      "obsidian"
      "vesktop"
      "zenmap"
    ];
    masApps = {
      DaisyDisk = 411643860;
      Vimari = 1480933944;
      "WiFi Explorer" = 494803304;
      "Reeder 5." = 1529448980;
      "Okta Extension App" = 1439967473;
    };
  };
}
